#!/bin/bash

# Force Fresh Deployment Script
# This script makes a small change and pushes to GitHub to trigger a fresh Vercel build

echo "🚀 Force Fresh Deployment Script"
echo "================================"
echo ""

# Check if we're in a git repository
if [ ! -d .git ]; then
    echo "❌ Error: Not a git repository"
    echo "Please run this script from your project root directory"
    exit 1
fi

# Check for uncommitted changes
if [[ -n $(git status -s) ]]; then
    echo "⚠️  Warning: You have uncommitted changes"
    echo ""
    git status -s
    echo ""
    read -p "Continue anyway? (y/N): " confirm
    if [[ $confirm != [yY] ]]; then
        echo "Aborted."
        exit 0
    fi
fi

# Add timestamp to trigger rebuild
echo "📝 Adding deployment timestamp..."
echo "# Last deployment: $(date)" >> .deployment-history
echo "✅ Timestamp added"

# Commit the change
echo ""
echo "💾 Creating commit..."
git add .deployment-history
git commit -m "Force fresh deployment - $(date +%Y-%m-%d\ %H:%M:%S)

This deployment was triggered to reload environment variables.
Environment variables in Next.js are embedded at build time.

🤖 Generated by force-deploy.sh script"

if [ $? -ne 0 ]; then
    echo "❌ Error: Failed to create commit"
    exit 1
fi
echo "✅ Commit created"

# Push to GitHub
echo ""
echo "🚀 Pushing to GitHub..."
git push

if [ $? -ne 0 ]; then
    echo "❌ Error: Failed to push to GitHub"
    echo "Please push manually: git push"
    exit 1
fi

echo ""
echo "✅ Successfully pushed to GitHub!"
echo ""
echo "📊 Next Steps:"
echo "1. Go to Vercel Dashboard: https://vercel.com/dashboard"
echo "2. Wait for deployment to complete (2-5 minutes)"
echo "3. Check deployment status in Vercel"
echo "4. Once deployed, visit: https://teddydecor.com"
echo "5. Hard refresh browser: Ctrl+Shift+R (Windows) or Cmd+Shift+R (Mac)"
echo "6. Go to Admin → Gallery and check Environment Diagnostic box"
echo "7. Upload a photo and verify it says 'Uploaded to cloud!'"
echo ""
echo "🎉 Deployment triggered successfully!"
